### PR TITLE
Changed messagecode for ActivateApp for revoked app

### PR DESCRIPTION
**Pull request by OlhaVorobiova**
Fixes [#12619](https://adc.luxoft.com/jira/browse/FORDTCN-12619)

This PR is **ready** for review.

### Summary
Message with AppUnauthorized code is more obvious for users when application is revoked.

### CODE REVIEW

**Review by VadymLuchko — APPROVED** [review]

**Review by ychernysheva — APPROVED** [review]

**Review by AKalinich-Luxoft — APPROVED** [review]

**Comment by vlrm10** [comment]
@OlhaVorobiova  has it been tested? There is no potential bugs after change `AppUnsupported` to `AppUnauthorized` ?

**Comment by vlrm10** [comment]
@OlhaVorobiova Do we need to provide the same changes in generic_hmi in [this line of code](https://github.com/LuxoftSDL/generic_hmi/blob/develop/src/js/Controllers/SDLController.js#L205) ?

**Comment by vlrm10** [comment]
> @OlhaVorobiova has it been tested? There is no potential bugs after change `AppUnsupported` to `AppUnauthorized` ?

I read the comments in jira. I agree wit the changes. But seems the fix is also applicable for generic_hmi

**Review by vlrm10 — APPROVED** [review]

**Comment by AKalinich-Luxoft** [comment]
> > @OlhaVorobiova has it been tested? There is no potential bugs after change `AppUnsupported` to `AppUnauthorized` ?
> 
> I read the comments in jira. I agree wit the changes. But seems the fix is also applicable for generic_hmi

@ValeriiMalkov good point. Please apply this one to generic as well

**Review by RomanReznichenkoLuxoft — APPROVED** [review]

**Comment by OlhaVorobiova** [comment]
moved to open

**Pull request closed without merging**
